@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lych.soulcraft.extension.control.attack;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;