@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lych.soulcraft.extension.highlight;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;