@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lych.soulcraft.extension.shield;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;