@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lych.soulcraft.util.redirectable;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;