@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lych.soulcraft.extension.soulpower;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;