@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lych.soulcraft.extension.laser;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;